version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
    command: "yarn dev"
    depends_on: 
      - db
  db:
    image: postgres:11
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bank_api_db
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "8080:15672"
      - "5672:5672"
      - "25676:25676"
  sonarqube:
    container_name:  sonarqube
    image:  sonarqube:latest
    ports:
      -  "9000:9000"
      -  "9092:9092"
